ALTER SESSION SET CONTAINER=CDB$ROOT;

ALTER PLUGGABLE DATABASE BANKING_PDB OPEN;
ALTER PLUGGABLE DATABASE BANKING_PDB SAVE STATE;

ALTER SESSION SET CONTAINER=BANKING_PDB;

BEGIN
EXECUTE IMMEDIATE 'DROP USER admin CASCADE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE USER admin IDENTIFIED BY 123;

CREATE TABLESPACE banking_ts
  DATAFILE '/opt/oracle/oradata/ORCLCDB/BANKING_PDB/banking_ts01.dbf'
  SIZE 200M
  AUTOEXTEND ON NEXT 50M
  MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;

ALTER USER admin DEFAULT TABLESPACE banking_ts
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON banking_ts;

GRANT CONNECT, RESOURCE, DBA TO admin;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO admin;

SELECT USER FROM dual;
